#general.import = [
#  "~/.config/alacritty/catppuccin-macchiato.toml"
#]


[font]
size = 14.0
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }

[window]
padding = { x = 15, y = 15 }

[colors.primary]
background = "#24273a"
foreground = "#cad2f5"
